### ISSUE TITLE
name 'MergeKey' is not defined

### ISSUE THREAD

**Issue by Liu131452** [kaiserpreusse/graphio#9]
![image](https://user-images.githubusercontent.com/84161060/185616529-05b3034b-9e84-479b-afc1-0efd29f09c3d.png)

**Comment by mpreusse** [comment]
The basic ORM functionality is based on py2neo. It is not clear how the development of py2neo will continue and I will switch to the official Neo4j Python driver as backend for graphio.

The ORM will be removed in one of the next releases, please consider it to be deprecated.
